apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: minta-gitops
  newName: docker.io/feketej/minta-gitops
  newTag: 6323b5f07f483228b7d13651f4899d39eb2a6cc5
- name: minta-gitops-app
  newName: docker.io/feketej/minta-gitops
  newTag: e8d7e7287928e458f0976ea777094206f5020bb5
